### ISSUE TITLE
路径嵌套问题

### ISSUE THREAD

**Issue by chrispher** [jack-zh/zwiki#1]
谢谢楼主分享，最近正在用你的框架搭建自己的wiki系统。
有一个小bug，就是如果md的文件路径超过两层，那么无法打开url。
查看了下，是model.py，167行`url = os.path.join(path_prefix[0], name[:-3])` 需要修改一下，在windows下，可以修改为`url = os.path.join('\\'.join(path_prefix) , name[:-3])`

期待楼主增加新功能！

**Comment by jack-zh** [comment]
请再次描述一下可以吗？是不是设置路径为多曾路径 比如`1/2/3` 出现的问题？
我这边没有重现，系统为linux和mac

**Comment by chrispher** [comment]
比如我的文件放在post下，那么post/data0/data1/data.md，在网页上显示的url链接打不开，url显示的是data1/data，少了一个data0。代码用`url = os.path.join('/'.join(path_prefix) , name[:-3])`也可以。

**Comment by jack-zh** [comment]
fix it, thanks chrispher.
